languageCode = "en-us"
title = "Sylvia P. Kinosian"
baseurl = "http://sylviakinosian.github.io/"
theme = "prologue"

[params]
  name = "Sylvia Kinosian"
  description = "PhD Student"
  copyright = "Sylvia Kinosian 2018"

[[params.social]]
  medium = "researchgate"
  icon = "researchgate"
  link = "https://www.researchgate.net/profile/Sylvia_Kinosian"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/sylviakinosian"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:sylvia.kinosian@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Polystichum hancockii"
  alt = ""
  source = "img/h1.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Dryopteris celsa"
  alt = "This is a tetraploid"
  source = "img/celsa.jpg"
  url = "http://www.fernsoftheworld.com/2015/07/04/dryopteris-celsa/"

# Portfolio column two

[[params.portfolio2]]
  title = "Selliguea parsifolia"
  alt = ""
  source = "img/sel.jpg"
  url = "#"

[[params.portfolio2]] 
  title = "Histiopteris incisa"
  alt = ""
  source = "img/hy.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Ceratopteris thalictroides"
  alt = ""
  source = "img/cer2.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Ceratopteris thalictroides"
  alt = ""
  source = "img/cer1.jpg"
  url = "#"
