languageCode = "en-us"
title = "Sylvia P. Kinosian"
baseurl = "http://sylviakinosian.github.io/"
theme = "prologue"

[params]
  name = "Sylvia Kinosian"
  description = "PhD Student"
  copyright = "Sylvia Kinosian 2018"

[[params.social]]
  medium = "researchgate"
  icon = "researchgate"
  link = "https://www.researchgate.net/profile/Sylvia_Kinosian"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/sylviakinosian"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:sylvia.kinosian@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
